# Generated by Django 5.0.7 on 2024-07-14 17:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('address_line_1', models.CharField(max_length=255, verbose_name='Адрес 1')),
                ('address_line_2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес 2')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('country', models.CharField(max_length=100, verbose_name='Страна')),
                ('postal_code', models.CharField(max_length=20, verbose_name='Почтовый индекс')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='Название документа')),
                ('file', models.FileField(upload_to='documents/', verbose_name='Файл')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('due_date', models.DateField(verbose_name='Срок оплаты')),
                ('paid', models.BooleanField(default=False, verbose_name='Оплачено')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, db_column='surname', db_comment='Информация о фамилии', max_length=50, null=True, verbose_name='Фамилия')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('age', models.PositiveSmallIntegerField(blank=True, editable=False, null=True, validators=[django.core.validators.MaxValueValidator(120)], verbose_name='Возраст')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profiles/', verbose_name='Фото профиля')),
                ('still_alive', models.BooleanField(default=True, verbose_name='Жив')),
                ('total_rating', models.FloatField(default=0.0, verbose_name='Общий рейтинг')),
            ],
            options={
                'db_table': 'person',
                'db_table_comment': 'Эта таблица содержит записи о людях',
                'get_latest_by': 'created_at',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Название проекта')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='Дата платежа')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Сумма')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='mymodels.invoice', verbose_name='Счёт')),
            ],
        ),
        migrations.AddConstraint(
            model_name='person',
            constraint=models.UniqueConstraint(fields=('first_name', 'last_name'), name='unique_person_name'),
        ),
        migrations.AddField(
            model_name='address',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='mymodels.person', verbose_name='Человек'),
        ),
        migrations.CreateModel(
            name='ProxyPerson',
            fields=[
            ],
            options={
                'ordering': ['-total_rating'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('mymodels.person',),
        ),
        migrations.AddField(
            model_name='project',
            name='team_members',
            field=models.ManyToManyField(related_name='projects', to='mymodels.person', verbose_name='Участники команды'),
        ),
        migrations.AddField(
            model_name='document',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='mymodels.project', verbose_name='Проект'),
        ),
    ]
